# to use with a reprap board connected first on USB port and an Arduino as ISP one secod USB port

# requires to install MightyCore definition :
# add download reference in ~/arduino-cli.yaml like explained here : https://github.com/MCUdude/MightyCore/issues/127#issuecomment-451514934
# arduino-cli core update-index
# arduino-cli core install MightyCore:avr

BOARD := MightyCore:avr:644
#:isp=arduino
ARDUINO_CLI_UPLOAD_OPTS := -P arduinoasisp
UPLOAD_PORT := /dev/ttyUSB1
PORT := /dev/ttyUSB0
LIBRARY_PATH := ~/GitHub/piif/ArduinoLibs ~/GitHub/piif/ArduinoTools ${PROJECT_DIR}
ARDDUDE_OPTIONS := -l lf -o raw -d -a "arduino-cli upload ${ARDUINO_CLI_UPLOAD_OPTS}"
#CFLAGS=-Dgcode_Buffer_size=7
