#MAIN_SOURCE:=epd2in13_V4.ino
LIBRARY_PATH=~/GitHub/piif/ArduinoLibs ~/GitHub/piif/ArduinoTools

# FOR LGT8F328
PORT := /dev/ttyUSB0
BOARD := lgt8fx:avr:328
BAUDRATE=115200

ARDDUDE_OPTIONS := -l cr -o raw -d
ARDUINO_CLI_UPLOAD_OPTS=-v
ARDUINO_CLI_COMPILE_OPTS=--warnings all --build-property "build.extra_flags=-DINCLUDE_FONT_12"
