BOARD := arduino:avr:uno
#BOARD := arduino:avr:nano:cpu=atmega328isp
ARDDUDE_OPTIONS := -l cr -o raw -d
PORT := /dev/ttyUSB0
LIBRARY_PATH := ..
ARDUINO_CLI_UPLOAD_OPTS=-v
ARDUINO_CLI_COMPILE_OPTS=--build-property "build.extra_flags=-DDS3231_DEBUG"
MAIN_SOURCE := example/example.ino